name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Deploy to AWS
        run: |
          # Install AWS CLI
          npm install -g aws-cli

          # Configure AWS CLI
          aws configure set aws_access_key_id ${{ secrets.CUSTOM_AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.CUSTOM_AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region us-west-1

          # Fetch secrets from AWS Secrets Manager
          export SECRETS_JSON=$(aws secretsmanager get-secret-value --secret-id ${{ secrets.SECRET_ID }} --query SecretString --output text)

          # Export secrets as environment variables
          export $(echo $SECRETS_JSON | jq -r "to_entries|map(\"\(.key)=\(.value|tostring)\")|.[]")

          # Deploy your app
          npm run start
        
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
          CUSTOM_AWS_ACCESS_KEY_ID: ${{ secrets.CUSTOM_AWS_ACCESS_KEY_ID }}
          CUSTOM_AWS_SECRET_ACCESS_KEY: ${{ secrets.CUSTOM_AWS_SECRET_ACCESS_KEY }}
          CUSTOM_AWS_BUCKET: ${{ secrets.CUSTOM_AWS_BUCKET }}
          CUSTOM_AWS_REGION: ${{ secrets.CUSTOM_AWS_REGION }}
          AI_TOKEN: ${{ secrets.AI_TOKEN }}
          SECRET_ID: your-secret-id
